name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - name: Clone Private Repository
        run: |
          git clone https://x-access-token:${{ secrets.PUBLIC_REPO }}@github.com/elonehoo/oicd-private-demo.git

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        working-directory: oicd-private-demo
        run: pnpm install

      - name: Upgrade npm
        run: npm i -g npm@latest

      - name: Publish to NPM
        working-directory: oicd-private-demo
        run: pnpm run publish:ci
